#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : jdk-fasterxml-oss-parent
Version  : 26
Release  : 1
URL      : https://github.com/FasterXML/oss-parent/archive/oss-parent-26.tar.gz
Source0  : https://github.com/FasterXML/oss-parent/archive/oss-parent-26.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: jdk-fasterxml-oss-parent-data
BuildRequires : apache-maven
BuildRequires : apache-maven2
BuildRequires : javapackages-tools
BuildRequires : jdk-aether
BuildRequires : jdk-aopalliance
BuildRequires : jdk-apache-parent
BuildRequires : jdk-aqute-bndlib
BuildRequires : jdk-atinject
BuildRequires : jdk-bsh
BuildRequires : jdk-build-helper-maven-plugin
BuildRequires : jdk-cdi-api
BuildRequires : jdk-commons-beanutils
BuildRequires : jdk-commons-cli
BuildRequires : jdk-commons-codec
BuildRequires : jdk-commons-collections
BuildRequires : jdk-commons-compress
BuildRequires : jdk-commons-digester
BuildRequires : jdk-commons-io
BuildRequires : jdk-commons-lang
BuildRequires : jdk-commons-lang3
BuildRequires : jdk-commons-logging
BuildRequires : jdk-commons-validator
BuildRequires : jdk-doxia
BuildRequires : jdk-doxia-integration-tools
BuildRequires : jdk-doxia-sitetools
BuildRequires : jdk-eclipse-eclipse
BuildRequires : jdk-eclipse-osgi
BuildRequires : jdk-eclipse-osgi-services
BuildRequires : jdk-felix
BuildRequires : jdk-felix-bundlerepository
BuildRequires : jdk-felix-framework
BuildRequires : jdk-felix-osgi-foundation
BuildRequires : jdk-felix-utils
BuildRequires : jdk-glassfish-servlet-api
BuildRequires : jdk-guava
BuildRequires : jdk-guice
BuildRequires : jdk-httpcomponents-client
BuildRequires : jdk-httpcomponents-core
BuildRequires : jdk-jsoup
BuildRequires : jdk-jsr-305
BuildRequires : jdk-kxml
BuildRequires : jdk-maven-archiver
BuildRequires : jdk-maven-bundle-plugin
BuildRequires : jdk-maven-dependency-tree
BuildRequires : jdk-maven-plugin-tools
BuildRequires : jdk-maven-reporting-api
BuildRequires : jdk-maven-reporting-exec
BuildRequires : jdk-maven-reporting-impl
BuildRequires : jdk-maven-shared-utils
BuildRequires : jdk-maven-site-plugin
BuildRequires : jdk-objectweb-asm
BuildRequires : jdk-osgi-compendium
BuildRequires : jdk-osgi-core
BuildRequires : jdk-parboiled
BuildRequires : jdk-pegdown
BuildRequires : jdk-plexus-archiver
BuildRequires : jdk-plexus-build-api
BuildRequires : jdk-plexus-cipher
BuildRequires : jdk-plexus-classworlds
BuildRequires : jdk-plexus-containers
BuildRequires : jdk-plexus-i18n
BuildRequires : jdk-plexus-interpolation
BuildRequires : jdk-plexus-io
BuildRequires : jdk-plexus-sec-dispatcher
BuildRequires : jdk-plexus-utils
BuildRequires : jdk-plexus-velocity
BuildRequires : jdk-sisu
BuildRequires : jdk-slf4j
BuildRequires : jdk-snappy
BuildRequires : jdk-velocity
BuildRequires : jdk-wagon
BuildRequires : jdk-xbean
BuildRequires : jdk-xmlunit
BuildRequires : jdk-xz
BuildRequires : lxml
BuildRequires : openjdk-dev
BuildRequires : python3
BuildRequires : six
BuildRequires : xmvn

%description
== Introduction ==
This project contains share parent POM for projects in FasterXML repository.

%package data
Summary: data components for the jdk-fasterxml-oss-parent package.
Group: Data

%description data
data components for the jdk-fasterxml-oss-parent package.


%prep
%setup -q -n oss-parent-oss-parent-26

python3 /usr/share/java-utils/pom_editor.py pom_remove_plugin  org.sonatype.plugins:nexus-maven-plugin
python3 /usr/share/java-utils/pom_editor.py pom_remove_plugin  :maven-scm-plugin
python3 /usr/share/java-utils/pom_editor.py pom_remove_plugin  org.codehaus.mojo:jdepend-maven-plugin
python3 /usr/share/java-utils/pom_editor.py pom_remove_plugin  org.codehaus.mojo:taglist-maven-plugin
python3 /usr/share/java-utils/pom_editor.py pom_xpath_remove   "pom:build/pom:extensions"
python3 /usr/share/java-utils/pom_editor.py pom_xpath_remove   "pom:reporting/pom:plugins/pom:plugin[pom:artifactId='maven-javadoc-plugin']/pom:configuration"
python3 /usr/share/java-utils/pom_editor.py pom_xpath_inject   "pom:reporting/pom:plugins/pom:plugin[pom:artifactId='maven-javadoc-plugin']" '
<configuration>
<encoding>UTF-8</encoding>
<quiet>true</quiet>
<source>${javac.src.version}</source>
</configuration>'
python3 /usr/share/java-utils/pom_editor.py pom_remove_plugin  :maven-enforcer-plugin

%build
python3 /usr/share/java-utils/mvn_build.py -j

%install
xmvn-install  -R .xmvn-reactor -n fasterxml-oss-parent -d %{buildroot}

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/maven-metadata/fasterxml-oss-parent.xml
/usr/share/maven-poms/fasterxml-oss-parent/oss-parent.pom
